name: Build and deploy npm package
description: |
  This action builds and publishes an npm package to GitHub Packages.
  It is intended for use in a CI/CD pipeline to automate the process of building and publishing a package.

inputs:
  node_version:
    description: 'Node.js version to use for the build'
    required: false
    default: '18.x'

  package_manager:
    description: 'Package manager to use (npm or yarn)'
    required: false
    default: 'npm'

  path_to_package_json:
    description: 'Path to package.json file'
    required: false
    default: './package.json'

  path_to_package_lock:
    description: 'Path to package-lock.json or yarn.lock file'
    required: false
    default: 'package-lock.json'

  registry_url:
    description: 'URL of the npm registry to publish to'
    required: false

  install_command:
    description: 'Command to install dependencies'
    required: false
    default: 'npm ci'

  build_command:
    description: 'Command to build the package'
    required: false
    default: 'npm run build'

  build_output_path:
    description: 'Path to the build output directory'
    required: false
    default: 'dist'

secrets:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true

  NPM_TOKEN:
    description: 'NPM token for publishing packages'
    required: true

on:
  workflow_call:

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: ${{ inputs.install_command }}
    
    - name: Build
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ${{ inputs.build_output_path }}
        retention-days: 2

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.package_manager }}
        cache-dependency-path: ${{ inputs.path_to_package_lock }}
        registry-url: ${{ inputs.registry_url }}

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: ${{ inputs.build_output_path }}

    - name: Setup git user info
      run: | 
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"   

    - name: Create version
      id: create_version
      run: npm run version:dev
    
    - name: Publish
      run: npm run version:publish:dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get package version
      id: package-version
      run: |
        path_to_package_json=${{ inputs.path_to_package_json }}
        PACKAGE_VERSION=$(node -p "require($path_to_package_json).version")
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

    - name: Set job summary
      run: |
        echo "## Package Version" >> $GITHUB_STEP_SUMMARY
        echo "- Version: ${{ steps.package-version.outputs.PACKAGE_VERSION }}" >> $GITHUB_STEP_SUMMARY
