name: Build and deploy npm package
description: |
  This action builds and publishes an npm package to GitHub Packages.
  It is intended for use in a CI/CD pipeline to automate the process of building and publishing a package.

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use for the build'
        required: false
        type: string
        default: '18.x'

      package_manager:
        description: 'Package manager to use (npm or yarn)'
        required: false
        type: string
        default: 'npm'

      path_to_package_json:
        description: 'Path to package.json file'
        required: false
        type: string
        default: './package.json'

      path_to_package_lock:
        description: 'Path to package-lock.json or yarn.lock file'
        required: false
        type: string
        default: 'package-lock.json'

      registry_url:
        description: 'URL of the npm registry to publish to'
        required: false
        type: string

      install_command:
        description: 'Command to install dependencies'
        required: false
        type: string
        default: 'npm ci'

      build_command:
        description: 'Command to build the package'
        required: false
        type: string
        default: 'npm run build'

      build_output_path:
        description: 'Path to the build output directory'
        required: false
        type: string
        default: 'dist'

      deployment_branch_name:
        description: 'Branch name for deployment'
        required: false
        type: string
        default: 'main'

      version_command:
        description: 'Command to create a version of the package'
        required: true
        type: string
      
      publish_command:
        description: 'Command to publish the package'
        required: true
        type: string

    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for authentication'
        required: true
        type: string

      NPM_TOKEN:
        description: 'NPM token for publishing packages'
        required: true
        type: string

      NODE_AUTH_TOKEN:
        description: 'Node authentication token for npm registry'
        required: true
        type: string

jobs:
  check-deployment-branch:
    name: Check deployment branch
    outputs:
      is_valid_branch: ${{ steps.check_branch.outputs.is_main }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check deployment branch
      id: check_branch
      run: |
        branch_name="${{ inputs.deployment_branch_name }}"
        if [ "${{ github.ref_name }}" != "$branch_name" ]; then
          echo "This workflow can only be run on the $branch_name branch."
          echo "is_valid_branch=false" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "This workflow is running on the main branch."
          echo "is_valid_branch=true" >> $GITHUB_OUTPUT
        fi
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check-deployment-branch
    if: needs.check-deployment-branch.outputs.is_valid_branch == 'true'

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: ${{ inputs.install_command }}
    
    - name: Build
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ${{ inputs.build_output_path }}
        retention-days: 2

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.package_manager }}
        cache-dependency-path: ${{ inputs.path_to_package_lock }}
        registry-url: ${{ inputs.registry_url }}

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: ${{ inputs.build_output_path }}

    - name: Setup git user info
      run: | 
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"   

    - name: Create version
      id: create_version
      run: ${{ inputs.version_command }}
    
    - name: Publish
      run: ${{ inputs.publish_command }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get package version
      id: package-version
      run: |
        path_to_package_json=${{ inputs.path_to_package_json }}
        PACKAGE_VERSION=$(node -p "require($path_to_package_json).version")
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

    - name: Set job summary
      run: |
        echo "## Package Version" >> $GITHUB_STEP_SUMMARY
        echo "- Version: ${{ steps.package-version.outputs.PACKAGE_VERSION }}" >> $GITHUB_STEP_SUMMARY
