name: Tag Version

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git user info
        run: | 
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" 

      - name: Tag the release
        id: tag-release
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Tagging release with version: $VERSION"
          git tag -a "$VERSION" -m "Release version $VERSION"
          git push origin "$VERSION"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set job summary
        run: |
          echo "## Package Version" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ steps.tag-release.outputs.version }}" >> $GITHUB_STEP_SUMMARY

        